#Name: Mohammad BoAisha
#Lab Sec. 226
#Lab 10

#XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXO
def get(xs, index, response=None):
    try:
        return xs[index]
    except IndexError:
        return response
#XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXO
def classify:
	pass
#XOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXOXO
def shelve(inventory, product_list):
	pass